version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  web:
    build: .
    command: python api/app.py
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    depends_on:
        - mongodb
  test:
    build: .
    command: python -m unittest discover -p "*.py" -s api.test
    ports:
        - "5000:5000"
    volumes:
        - .:/code
    depends_on:
        - mongodb
